name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout 
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build image 
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/test:latest .
      
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/test:lastest

      - name: Remove previous image
        run: |
          if [ -f ".previous_tag" ]; then
            PREVIOUS_TAG=$(cat .previous_tag)
            echo "Removing previous image: ${{ secrets.DOCKER_USERNAME }}/your-image-name:$PREVIOUS_TAG"
            curl -s -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_ACCESS_TOKEN }} \
              -X DELETE "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/test/tags/$PREVIOUS_TAG/"
          fi
