name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout 
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      
      - name: Extract commit message
        id: get_commit
        run: echo "COMMIT_MSG=$(git log -1 --pretty=%B | tr -d '\n' | tr ' ' '-')" >> $GITHUB_ENV

      - name: Build image 
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/test:${{ env.COMMIT_MSG }} .
      
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/test:${{ env.COMMIT_MSG }}

      - name: Remove previous image
        run: |
          if [ -f ".previous_tag" ]; then
            PREVIOUS_TAG=$(cat .previous_tag)
            echo "Removing previous image: ${{ secrets.DOCKER_USERNAME }}/your-image-name:$PREVIOUS_TAG"
            curl -s -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_ACCESS_TOKEN }} \
              -X DELETE "https://hub.docker.com/v2/repositories/${{ secrets.DOCKER_USERNAME }}/test/tags/$PREVIOUS_TAG/"
          fi

      - name: Save current tag for future reference
        run: echo ${{ env.COMMIT_MSG }} > .previous_tag
        continue-on-error: true

      - name: Upload previous tag artifact
        uses: actions/upload-artifact@v3
        with:
          name: previous-tag
          path: .previous_tag