name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout 
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build image 
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/test:latest .
      
      - name: Push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/test:latest
